# Generated by Django 4.2 on 2024-05-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementCategory',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planificacion_slug', models.CharField(blank=True, default='', max_length=1024)),
                ('convocatoria_slug', models.CharField(blank=True, default='', max_length=1024)),
                ('adjudicacion_slug', models.CharField(blank=True, default='', max_length=1024)),
                ('precalificacion_slug', models.CharField(blank=True, default='', max_length=1024)),
                ('convenio_slug', models.CharField(blank=True, default='', max_length=1024)),
                ('nro_licitacion', models.CharField(blank=True, default='', max_length=1024)),
                ('nombre_licitacion', models.CharField(blank=True, default='', max_length=1024)),
                ('tipo_procedimiento', models.CharField(blank=True, default='', max_length=1024)),
                ('categoria', models.CharField(blank=True, default='', max_length=1024)),
                ('convocante', models.CharField(blank=True, default='', max_length=1024)),
                ('_etapa_licitacion', models.CharField(blank=True, default='', max_length=1024)),
                ('etapa_licitacion', models.CharField(blank=True, default='', max_length=1024)),
                ('fecha_entrega_oferta', models.DateTimeField(blank=True, null=True)),
                ('tipo_licitacion', models.CharField(blank=True, default='', max_length=1024)),
                ('fecha_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_publicacion_convocatoria', models.DateTimeField(blank=True, null=True)),
                ('geo', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
    ]
