"""
Django settings for BidMaster project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!d6pv5guaf7dxmff1azyr@)#^azrzrw=(nc0+f@3j6*#!nv+iy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'usuarios.Usuario'

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

ACCOUNT_ADAPTER = 'usuarios.adapters.CustomSocialAccountAdapter'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'

SOCIALACCOUNT_PROVIDERS = {
    'keycloak': {
        'KEY': 'myclient',
        'SECRET': 'z8WlX5KrCcaWpd2ZipI495IOvamDGCcn',
        'AUTH_PARAMS': {
            'scope': 'openid email profile'
        },
        'OIDC_ENDPOINT': 'http://localhost:8080/auth/realms/your-realm',
        'OAUTH2_TOKEN_URL': 'http://localhost:8080/auth/realms/BidMaster/protocol/openid-connect/token',
        'OAUTH2_AUTHORIZE_URL': 'http://localhost:8080/auth/realms/BidMaster/protocol/openid-connect/auth',
        'OAUTH2_USERINFO_URL': 'http://localhost:8080/auth/realms/BidMaster/protocol/openid-connect/userinfo',
        'OAUTH2_LOGOUT_URL': 'http://localhost:8080/auth/realms/BidMaster/protocol/openid-connect/logout'
    }
}

# SOCIALACCOUNT_PROVIDERS = {
#     'openid_connect': {
#         'SERVERS': [
#             {
#                 'id': 'keycloak',
#                 'name': 'Keycloak',
#                 'server_url': 'http://localhost:8080/auth/',
#                 'client_id': 'myclient',
#                 'secret': 'z8WlX5KrCcaWpd2ZipI495IOvamDGCcn',
#                 'key': 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsrdVTvIQmNMdo1FJUX7qEGnkyJe+GeaCByCE2p4udoWvaUC9pP+wniwicjQyq5psKjNF65F1yTXxVpwfZydnQZw2CVeAHB09BGuLc5kkeuiE05ubJdCsfzmNVUDoQPme+KDQ2depcx/U61Yn48wu/rrtfr8vvmN0BvVgLSVXOphl1cYCFQdbWSQASjWg7l35dBJN17/WVwV28LSXARhxOzH7eeMsuaG/QIq3O32yI9ewzBigThYyIk0+SnVDZuZNGQb6uteR5X/UNP8C57jlh1fIGZhmIZ+JGohx8i7k/3pZtJG7RUkxyRxbroLaYgUsRph/N+gBOdHitXDIlzxBGwIDAQAB',
#                 'prompt': 'select_account',
#                 'scopes': ['openid', 'profile', 'email'],
#             }
#         ]
#     }
# }

SOCIALACCOUNT_ADAPTER = 'your_app.adapters.CustomSocialAccountAdapter'

# Application definition

INSTALLED_APPS = [
    'licitaciones.apps.LicitacionesConfig',
    'usuarios',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
    'allauth.socialaccount.providers.keycloak',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'BidMaster.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'usuarios/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BidMaster.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'licitacionesdev',
        'USER': 'djangodev',
        'PASSWORD': '321654',
        'HOST': '127.0.0.1',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Asuncion'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
